# services to handle doctrine extensions
# import it in config/packages/doctrine_extensions.yaml
services:
    Gedmo\Translatable\TranslatableListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            - [ setDefaultLocale, [ '%kernel.default_locale%' ] ]
            - [ setTranslationFallback, [ false ] ]

